# .github/workflows/oidc-sub-debug.yml
name: oidc-sub-debug
on: workflow_dispatch
permissions:
  id-token: write
  contents: read

jobs:
  show-claims:
    runs-on: ubuntu-latest
    environment: dev   # prod'u test etmek istersen prod yap
    steps:
      - name: Fetch OIDC token and print claims
        shell: bash
        run: |
          set -euo pipefail
          # 1) GitHub OIDC endpoint'inden token al (audience = sts.amazonaws.com)
          resp=$(curl -sS -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
                       "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com")
          token=$(echo "$resp" | jq -r '.value')
          echo "RAW_JWT_LENGTH=${#token}"

          # 2) JWT payload'ı decode edip sub ve aud'u yazdır
          TOKEN="$token" python3 - <<'PY'
import os, base64, json
tok = os.environ["TOKEN"]
payload_b64 = tok.split('.')[1]
payload_b64 += '=' * (-len(payload_b64) % 4)  # base64url padding
payload = base64.urlsafe_b64decode(payload_b64).decode()
data = json.loads(payload)
print("SUB:", data.get("sub"))
print("AUD:", data.get("aud"))
print("FULL PAYLOAD:")
print(json.dumps(data, indent=2))
PY
